# Generated by Django 5.1.1 on 2026-02-10 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('extracted_skills', models.JSONField(blank=True, default=list)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('match_score', models.FloatField(default=0)),
                ('decision', models.CharField(blank=True, choices=[('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected')], max_length=20, null=True)),
                ('screened_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='candidates.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='jobs.job')),
            ],
            options={
                'ordering': ['-screened_at', '-id'],
            },
        ),
    ]
