# Generated by Django 4.2.28 on 2026-02-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
    ]
