# Generated by Django 5.1.1 on 2026-02-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0002_resume_error_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="ner_bonus",
            field=models.FloatField(default=0.0),
        ),
    ]
