# Generated by Django 5.1.1 on 2026-02-10 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('resume_path', models.CharField(help_text="Path or identifier for the candidate's resume (PDF only).", max_length=512)),
                ('match_score', models.FloatField(blank=True, help_text='Optional match score in percentage (0-100).', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_job', models.ForeignKey(help_text='The job the candidate applied for.', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
