# Generated by Django 4.2.28 on 2026-02-16 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="department",
            field=models.CharField(
                blank=True,
                help_text="Department name, e.g. 'Engineering', 'Marketing', 'Sales'",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.TextField(
                default="Job description pending",
                help_text="Detailed job description including responsibilities and requirements",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Job location, e.g. 'Remote', 'Bengaluru (Hybrid)', 'New York Office'",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("filled", "Filled"),
                ],
                default="draft",
                help_text="Current status of the job posting",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="required_experience",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Required experience in years (leave empty for fresher positions)",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(
                help_text="Job title, e.g. 'Senior Python Developer'", max_length=255
            ),
        ),
    ]
